language: node_js

node_js:
  - 'stable'
  - '6'

install:
  - npm install -g codecov
  - npm install

script:
  - npm test

# Send coverage data to Codecov
after_success: npm run coverage

notifications:
  email: false
